name: Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci --legacy-peer-deps

      - name: Create Schema
        run: |
          cat > schema.gql << EOL
          type MarkdownRemarkFrontmatter {
            path: String
            title: String
            hidden: Boolean
            course_info_page: Boolean
            sidebar_priority: Int
            hide_in_sidebar: Boolean
            overview: Boolean
            information_page: Boolean
            upcoming: Boolean
            vocabulary_page: Boolean
          }

          type MarkdownRemark implements Node {
            frontmatter: MarkdownRemarkFrontmatter
          }
          EOL

      - name: Build
        run: |
          gatsby clean
          gatsby build --prefix-paths
        env:
          GATSBY_TELEMETRY_DISABLED: 1
          NODE_ENV: production
          GATSBY_EXPERIMENTAL_TYPES_FOR_GRAPHQL: true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
